---
namespace: cisco
name: nso
# The version of the collection. Must be compatible with semantic versioning
version: 1.0.4
readme: README.md
authors:
- "Claes Nästén (@cnasten)"
description: Ansible Modules for Cisco NSO
license_file: 'LICENSE'
tags: 
- cisco
- nso
- cloud
- collection
- networking
repository: https://github.com/CiscoDevNet/ansible-nso
documentation: https://developer.cisco.com/docs/nso/
homepage: https://github.com/CiscoDevNet/ansible-nso
issues: https://github.com/CiscoDevNet/ansible-nso/issues
